"""AI-1(bfs/dfs).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OfhhaPENG-xkad-aCeZHcCSHUb_EaLBE
"""

# allows us to create a dictionary with default values for new keys
from collections import defaultdict

class Graph:
    # initializes an empty graph
    def __init__(self):
        self.graph = defaultdict(list)
        # the self parameter is used to refer to the specific instance of the class that the method is being called on

    # used to add an undirected edge between two vertices u and v
    def add_edge(self, u, v):
        self.graph[u].append(v)
        self.graph[v].append(u)

    # It adds v to the visited set, prints v, 
    def dfs_util(self, v, visited):
        visited.add(v)
        print(v, end=" ")
        #and recursively calls itself for all unvisited neighbors of v
        for neighbor in self.graph[v]:
            if neighbor not in visited:
                self.dfs_util(neighbor, visited)

    # The dfs method initiates the DFS traversal by creating an empty visited set and calling dfs_util with the starting vertex.
    def dfs(self, start):
        visited = set()
        self.dfs_util(start, visited)
        # a stack is implemented using a list object


    # The bfs method performs the BFS traversal using a queue
    def bfs(self, start):
        visited = set()
        queue = [start]
        visited.add(start)
        # while loop that continues until the queue is empty
        while queue:
            # In each iteration, it dequeues a vertex from the front of the queue, prints it, and adds it to the visited set
            vertex = queue.pop(0)
            print(vertex, end=" ")
            # Finding all the neighbours of dequed vertex
            for neighbor in self.graph[vertex]:
                if neighbor not in visited:
                    queue.append(neighbor)
                    visited.add(neighbor)

# Create a graph object
graph = Graph()

# Get the number of edges from the user
num_edges = int(input("Enter the number of edges: "))

# Get the edges from the user
for _ in range(num_edges):
    u, v = input("Enter an edge (u v): ").split()
    graph.add_edge(u, v)

# Get the starting vertex for traversal
start_vertex = input("Enter the starting vertex: ")

# Perform DFS and BFS
print("Depth First Search (DFS):")
graph.dfs(start_vertex)

print("\nBreadth First Search (BFS):")
graph.bfs(start_vertex)